<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <StartupObject>PasteAsFile.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyTitle>PasteAsFile</AssemblyTitle>
    <AssemblyName>PasteAsFile</AssemblyName>
    <RootNamespace>PasteAsFile</RootNamespace>
    <Description>Paste Clipboard Contents into Files</Description>
    <Product>PasteAsFile v2 (madeByDast)</Product>
    <Company>EslaMxSoft 2014, madeByDast</Company>
    <Copyright>Copyright © EslaMxSoft 2014, madeByDast</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <Target Name="CleanAll" AfterTargets="Clean">
    <RemoveDir Directories="$(BaseOutputPath);$(BaseIntermediateOutputPath)" />
  </Target>

</Project>
